### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dipterix** [HenrikBengtsson/aroma.core#27]
`install.packages("aroma.core")` raises error:

```
ERROR: dependencies ‘aroma.light’, ‘DNAcopy’ are not available for package ‘PSCBS’
```

**Comment by HenrikBengtsson** [comment]
Yes, this is the unfortunate side-effect of depending on packages from Bioconductor.

Install those two packages from Bioconductor first. Then you should be able to install aroma.core.

**Comment by HenrikBengtsson** [comment]
FWIW, the README now explains this, cf. https://github.com/HenrikBengtsson/aroma.core#installation.

Next step here is to:

* [x] Incorporate the `README.md` file in the package so it shows up on the CRAN package page.

Alternatively, one can add a standalone 'How to install' vignette.

**Comment by HenrikBengtsson** [comment]
The [README](https://github.com/HenrikBengtsson/aroma.core#readme) now contains this information and will also be part of the package tarball, i.e. it'll end up on CRAN page https://cran.r-project.org/package=aroma.core.
